// Code generated by counterfeiter. DO NOT EDIT.
package repositoryfakes

import (
	"sync"

	"github.com/cf-platform-eng/kibosh/helm"
	"github.com/cf-platform-eng/kibosh/repository"
)

type FakeRepository struct {
	LoadChartsStub        func() ([]*helm.MyChart, error)
	loadChartsMutex       sync.RWMutex
	loadChartsArgsForCall []struct{}
	loadChartsReturns     struct {
		result1 []*helm.MyChart
		result2 error
	}
	loadChartsReturnsOnCall map[int]struct {
		result1 []*helm.MyChart
		result2 error
	}
	SaveChartStub        func(path string) error
	saveChartMutex       sync.RWMutex
	saveChartArgsForCall []struct {
		path string
	}
	saveChartReturns struct {
		result1 error
	}
	saveChartReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteChartStub        func(name string) error
	deleteChartMutex       sync.RWMutex
	deleteChartArgsForCall []struct {
		name string
	}
	deleteChartReturns struct {
		result1 error
	}
	deleteChartReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRepository) LoadCharts() ([]*helm.MyChart, error) {
	fake.loadChartsMutex.Lock()
	ret, specificReturn := fake.loadChartsReturnsOnCall[len(fake.loadChartsArgsForCall)]
	fake.loadChartsArgsForCall = append(fake.loadChartsArgsForCall, struct{}{})
	fake.recordInvocation("LoadCharts", []interface{}{})
	fake.loadChartsMutex.Unlock()
	if fake.LoadChartsStub != nil {
		return fake.LoadChartsStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.loadChartsReturns.result1, fake.loadChartsReturns.result2
}

func (fake *FakeRepository) LoadChartsCallCount() int {
	fake.loadChartsMutex.RLock()
	defer fake.loadChartsMutex.RUnlock()
	return len(fake.loadChartsArgsForCall)
}

func (fake *FakeRepository) LoadChartsReturns(result1 []*helm.MyChart, result2 error) {
	fake.LoadChartsStub = nil
	fake.loadChartsReturns = struct {
		result1 []*helm.MyChart
		result2 error
	}{result1, result2}
}

func (fake *FakeRepository) LoadChartsReturnsOnCall(i int, result1 []*helm.MyChart, result2 error) {
	fake.LoadChartsStub = nil
	if fake.loadChartsReturnsOnCall == nil {
		fake.loadChartsReturnsOnCall = make(map[int]struct {
			result1 []*helm.MyChart
			result2 error
		})
	}
	fake.loadChartsReturnsOnCall[i] = struct {
		result1 []*helm.MyChart
		result2 error
	}{result1, result2}
}

func (fake *FakeRepository) SaveChart(path string) error {
	fake.saveChartMutex.Lock()
	ret, specificReturn := fake.saveChartReturnsOnCall[len(fake.saveChartArgsForCall)]
	fake.saveChartArgsForCall = append(fake.saveChartArgsForCall, struct {
		path string
	}{path})
	fake.recordInvocation("SaveChart", []interface{}{path})
	fake.saveChartMutex.Unlock()
	if fake.SaveChartStub != nil {
		return fake.SaveChartStub(path)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.saveChartReturns.result1
}

func (fake *FakeRepository) SaveChartCallCount() int {
	fake.saveChartMutex.RLock()
	defer fake.saveChartMutex.RUnlock()
	return len(fake.saveChartArgsForCall)
}

func (fake *FakeRepository) SaveChartArgsForCall(i int) string {
	fake.saveChartMutex.RLock()
	defer fake.saveChartMutex.RUnlock()
	return fake.saveChartArgsForCall[i].path
}

func (fake *FakeRepository) SaveChartReturns(result1 error) {
	fake.SaveChartStub = nil
	fake.saveChartReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepository) SaveChartReturnsOnCall(i int, result1 error) {
	fake.SaveChartStub = nil
	if fake.saveChartReturnsOnCall == nil {
		fake.saveChartReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveChartReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepository) DeleteChart(name string) error {
	fake.deleteChartMutex.Lock()
	ret, specificReturn := fake.deleteChartReturnsOnCall[len(fake.deleteChartArgsForCall)]
	fake.deleteChartArgsForCall = append(fake.deleteChartArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("DeleteChart", []interface{}{name})
	fake.deleteChartMutex.Unlock()
	if fake.DeleteChartStub != nil {
		return fake.DeleteChartStub(name)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.deleteChartReturns.result1
}

func (fake *FakeRepository) DeleteChartCallCount() int {
	fake.deleteChartMutex.RLock()
	defer fake.deleteChartMutex.RUnlock()
	return len(fake.deleteChartArgsForCall)
}

func (fake *FakeRepository) DeleteChartArgsForCall(i int) string {
	fake.deleteChartMutex.RLock()
	defer fake.deleteChartMutex.RUnlock()
	return fake.deleteChartArgsForCall[i].name
}

func (fake *FakeRepository) DeleteChartReturns(result1 error) {
	fake.DeleteChartStub = nil
	fake.deleteChartReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepository) DeleteChartReturnsOnCall(i int, result1 error) {
	fake.DeleteChartStub = nil
	if fake.deleteChartReturnsOnCall == nil {
		fake.deleteChartReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteChartReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.loadChartsMutex.RLock()
	defer fake.loadChartsMutex.RUnlock()
	fake.saveChartMutex.RLock()
	defer fake.saveChartMutex.RUnlock()
	fake.deleteChartMutex.RLock()
	defer fake.deleteChartMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.Repository = new(FakeRepository)
