// Code generated by counterfeiter. DO NOT EDIT.
package cffakes

import (
	"sync"

	"github.com/cf-platform-eng/kibosh/pkg/cf"
	cfclient "github.com/cloudfoundry-community/go-cfclient"
)

type FakeClient struct {
	GetServiceBrokerByNameStub        func(name string) (cfclient.ServiceBroker, error)
	getServiceBrokerByNameMutex       sync.RWMutex
	getServiceBrokerByNameArgsForCall []struct {
		name string
	}
	getServiceBrokerByNameReturns struct {
		result1 cfclient.ServiceBroker
		result2 error
	}
	getServiceBrokerByNameReturnsOnCall map[int]struct {
		result1 cfclient.ServiceBroker
		result2 error
	}
	CreateServiceBrokerStub        func(csb cfclient.CreateServiceBrokerRequest) (cfclient.ServiceBroker, error)
	createServiceBrokerMutex       sync.RWMutex
	createServiceBrokerArgsForCall []struct {
		csb cfclient.CreateServiceBrokerRequest
	}
	createServiceBrokerReturns struct {
		result1 cfclient.ServiceBroker
		result2 error
	}
	createServiceBrokerReturnsOnCall map[int]struct {
		result1 cfclient.ServiceBroker
		result2 error
	}
	UpdateServiceBrokerStub        func(guid string, csb cfclient.UpdateServiceBrokerRequest) (cfclient.ServiceBroker, error)
	updateServiceBrokerMutex       sync.RWMutex
	updateServiceBrokerArgsForCall []struct {
		guid string
		csb  cfclient.UpdateServiceBrokerRequest
	}
	updateServiceBrokerReturns struct {
		result1 cfclient.ServiceBroker
		result2 error
	}
	updateServiceBrokerReturnsOnCall map[int]struct {
		result1 cfclient.ServiceBroker
		result2 error
	}
	DeleteServiceBrokerStub        func(guid string) error
	deleteServiceBrokerMutex       sync.RWMutex
	deleteServiceBrokerArgsForCall []struct {
		guid string
	}
	deleteServiceBrokerReturns struct {
		result1 error
	}
	deleteServiceBrokerReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) GetServiceBrokerByName(name string) (cfclient.ServiceBroker, error) {
	fake.getServiceBrokerByNameMutex.Lock()
	ret, specificReturn := fake.getServiceBrokerByNameReturnsOnCall[len(fake.getServiceBrokerByNameArgsForCall)]
	fake.getServiceBrokerByNameArgsForCall = append(fake.getServiceBrokerByNameArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("GetServiceBrokerByName", []interface{}{name})
	fake.getServiceBrokerByNameMutex.Unlock()
	if fake.GetServiceBrokerByNameStub != nil {
		return fake.GetServiceBrokerByNameStub(name)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getServiceBrokerByNameReturns.result1, fake.getServiceBrokerByNameReturns.result2
}

func (fake *FakeClient) GetServiceBrokerByNameCallCount() int {
	fake.getServiceBrokerByNameMutex.RLock()
	defer fake.getServiceBrokerByNameMutex.RUnlock()
	return len(fake.getServiceBrokerByNameArgsForCall)
}

func (fake *FakeClient) GetServiceBrokerByNameArgsForCall(i int) string {
	fake.getServiceBrokerByNameMutex.RLock()
	defer fake.getServiceBrokerByNameMutex.RUnlock()
	return fake.getServiceBrokerByNameArgsForCall[i].name
}

func (fake *FakeClient) GetServiceBrokerByNameReturns(result1 cfclient.ServiceBroker, result2 error) {
	fake.GetServiceBrokerByNameStub = nil
	fake.getServiceBrokerByNameReturns = struct {
		result1 cfclient.ServiceBroker
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetServiceBrokerByNameReturnsOnCall(i int, result1 cfclient.ServiceBroker, result2 error) {
	fake.GetServiceBrokerByNameStub = nil
	if fake.getServiceBrokerByNameReturnsOnCall == nil {
		fake.getServiceBrokerByNameReturnsOnCall = make(map[int]struct {
			result1 cfclient.ServiceBroker
			result2 error
		})
	}
	fake.getServiceBrokerByNameReturnsOnCall[i] = struct {
		result1 cfclient.ServiceBroker
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) CreateServiceBroker(csb cfclient.CreateServiceBrokerRequest) (cfclient.ServiceBroker, error) {
	fake.createServiceBrokerMutex.Lock()
	ret, specificReturn := fake.createServiceBrokerReturnsOnCall[len(fake.createServiceBrokerArgsForCall)]
	fake.createServiceBrokerArgsForCall = append(fake.createServiceBrokerArgsForCall, struct {
		csb cfclient.CreateServiceBrokerRequest
	}{csb})
	fake.recordInvocation("CreateServiceBroker", []interface{}{csb})
	fake.createServiceBrokerMutex.Unlock()
	if fake.CreateServiceBrokerStub != nil {
		return fake.CreateServiceBrokerStub(csb)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createServiceBrokerReturns.result1, fake.createServiceBrokerReturns.result2
}

func (fake *FakeClient) CreateServiceBrokerCallCount() int {
	fake.createServiceBrokerMutex.RLock()
	defer fake.createServiceBrokerMutex.RUnlock()
	return len(fake.createServiceBrokerArgsForCall)
}

func (fake *FakeClient) CreateServiceBrokerArgsForCall(i int) cfclient.CreateServiceBrokerRequest {
	fake.createServiceBrokerMutex.RLock()
	defer fake.createServiceBrokerMutex.RUnlock()
	return fake.createServiceBrokerArgsForCall[i].csb
}

func (fake *FakeClient) CreateServiceBrokerReturns(result1 cfclient.ServiceBroker, result2 error) {
	fake.CreateServiceBrokerStub = nil
	fake.createServiceBrokerReturns = struct {
		result1 cfclient.ServiceBroker
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) CreateServiceBrokerReturnsOnCall(i int, result1 cfclient.ServiceBroker, result2 error) {
	fake.CreateServiceBrokerStub = nil
	if fake.createServiceBrokerReturnsOnCall == nil {
		fake.createServiceBrokerReturnsOnCall = make(map[int]struct {
			result1 cfclient.ServiceBroker
			result2 error
		})
	}
	fake.createServiceBrokerReturnsOnCall[i] = struct {
		result1 cfclient.ServiceBroker
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) UpdateServiceBroker(guid string, csb cfclient.UpdateServiceBrokerRequest) (cfclient.ServiceBroker, error) {
	fake.updateServiceBrokerMutex.Lock()
	ret, specificReturn := fake.updateServiceBrokerReturnsOnCall[len(fake.updateServiceBrokerArgsForCall)]
	fake.updateServiceBrokerArgsForCall = append(fake.updateServiceBrokerArgsForCall, struct {
		guid string
		csb  cfclient.UpdateServiceBrokerRequest
	}{guid, csb})
	fake.recordInvocation("UpdateServiceBroker", []interface{}{guid, csb})
	fake.updateServiceBrokerMutex.Unlock()
	if fake.UpdateServiceBrokerStub != nil {
		return fake.UpdateServiceBrokerStub(guid, csb)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.updateServiceBrokerReturns.result1, fake.updateServiceBrokerReturns.result2
}

func (fake *FakeClient) UpdateServiceBrokerCallCount() int {
	fake.updateServiceBrokerMutex.RLock()
	defer fake.updateServiceBrokerMutex.RUnlock()
	return len(fake.updateServiceBrokerArgsForCall)
}

func (fake *FakeClient) UpdateServiceBrokerArgsForCall(i int) (string, cfclient.UpdateServiceBrokerRequest) {
	fake.updateServiceBrokerMutex.RLock()
	defer fake.updateServiceBrokerMutex.RUnlock()
	return fake.updateServiceBrokerArgsForCall[i].guid, fake.updateServiceBrokerArgsForCall[i].csb
}

func (fake *FakeClient) UpdateServiceBrokerReturns(result1 cfclient.ServiceBroker, result2 error) {
	fake.UpdateServiceBrokerStub = nil
	fake.updateServiceBrokerReturns = struct {
		result1 cfclient.ServiceBroker
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) UpdateServiceBrokerReturnsOnCall(i int, result1 cfclient.ServiceBroker, result2 error) {
	fake.UpdateServiceBrokerStub = nil
	if fake.updateServiceBrokerReturnsOnCall == nil {
		fake.updateServiceBrokerReturnsOnCall = make(map[int]struct {
			result1 cfclient.ServiceBroker
			result2 error
		})
	}
	fake.updateServiceBrokerReturnsOnCall[i] = struct {
		result1 cfclient.ServiceBroker
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) DeleteServiceBroker(guid string) error {
	fake.deleteServiceBrokerMutex.Lock()
	ret, specificReturn := fake.deleteServiceBrokerReturnsOnCall[len(fake.deleteServiceBrokerArgsForCall)]
	fake.deleteServiceBrokerArgsForCall = append(fake.deleteServiceBrokerArgsForCall, struct {
		guid string
	}{guid})
	fake.recordInvocation("DeleteServiceBroker", []interface{}{guid})
	fake.deleteServiceBrokerMutex.Unlock()
	if fake.DeleteServiceBrokerStub != nil {
		return fake.DeleteServiceBrokerStub(guid)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.deleteServiceBrokerReturns.result1
}

func (fake *FakeClient) DeleteServiceBrokerCallCount() int {
	fake.deleteServiceBrokerMutex.RLock()
	defer fake.deleteServiceBrokerMutex.RUnlock()
	return len(fake.deleteServiceBrokerArgsForCall)
}

func (fake *FakeClient) DeleteServiceBrokerArgsForCall(i int) string {
	fake.deleteServiceBrokerMutex.RLock()
	defer fake.deleteServiceBrokerMutex.RUnlock()
	return fake.deleteServiceBrokerArgsForCall[i].guid
}

func (fake *FakeClient) DeleteServiceBrokerReturns(result1 error) {
	fake.DeleteServiceBrokerStub = nil
	fake.deleteServiceBrokerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DeleteServiceBrokerReturnsOnCall(i int, result1 error) {
	fake.DeleteServiceBrokerStub = nil
	if fake.deleteServiceBrokerReturnsOnCall == nil {
		fake.deleteServiceBrokerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteServiceBrokerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getServiceBrokerByNameMutex.RLock()
	defer fake.getServiceBrokerByNameMutex.RUnlock()
	fake.createServiceBrokerMutex.RLock()
	defer fake.createServiceBrokerMutex.RUnlock()
	fake.updateServiceBrokerMutex.RLock()
	defer fake.updateServiceBrokerMutex.RUnlock()
	fake.deleteServiceBrokerMutex.RLock()
	defer fake.deleteServiceBrokerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cf.Client = new(FakeClient)
