---

resources:
- name: source-repo
  type: git
  source:
    branch: master
    uri: https://github.com/cf-platform-eng/kibosh
    username: cf-pe-bot
    password: {{github_token}}

jobs:
- name: unit-tests
  plan:
  - aggregate:
    - get: source-repo
      trigger: true
  - task: run-tests
    config:
      inputs:
      - name: source-repo
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: "1.9"
      run:
        path: bash
        args:
        - -exc
        - |
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega

          export SRC=/go/src/github.com/cf-platform-eng/kibosh
          mkdir -p $SRC
          cp -r source-repo/* $SRC
          cd $SRC
          make test
